---
version: "3"
networks:
  net_overseer: null
volumes:
  vol_nginx:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/nginx/run
      o: bind
  vol_overseerr:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/overseerr/run
      o: bind
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - vol_nginx:/data
    networks:
      net_overseer: null
    labels:
      - com.centurylinklabs.watchtower.enable=true
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_overseerr:/config
    ports:
      - 9898:9898
    networks:
      net_overseer: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
