---
volumes:
  vol_qbt_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/qbt/run/config
      o: bind
  vol_media:
    driver: local
    driver_opts:
      type: none
      device: /mnt/something/content
      o: bind

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - WEBUI_PORT=8899
    volumes:
      - vol_qbt_data:/config
      - vol_media:/media
    ports:
      - 8899:8899
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
