---
version: "3"
networks:
  net_sonarr: null
  net_radarr: null
volumes:
  vol_downloads:
    driver: local
    driver_opts:
      type: none
      device: /mnt/something/content
      o: bind
  vol_media:
    driver: local
    driver_opts:
      type: none
      device: /mnt/something/content
      o: bind
  vol_sonarr:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/sonarr/run
      o: bind
  vol_radarr:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/radarr/run
      o: bind
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_sonarr:/config
      - vol_media:/media
      - vol_downloads:/downloads
    ports:
      - 7878:7878
    networks:
      net_sonarr: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_radarr:/config
      - vol_media:/media
      - vol_downloads:/downloads
    ports:
      - 8989:8989
    networks:
      net_radarr: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
