---
version: "3"
networks:
  net_sabnzbd: null
volumes:
  vol_downloads:
    driver: local
    driver_opts:
      type: none
      device: /mnt/download
      o: bind
  vol_media:
    driver: local
    driver_opts:
      type: none
      device: /mnt/media
      o: bind
  vol_nginx:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/nginx
      o: bind
  vol_sabnzbd:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/sabnzbd/run/
      o: bind
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - vol_nginx:/data
    networks:
      net_sabnzbd: null
    labels:
      - com.centurylinklabs.watchtower.enable=true
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: always    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - vol_sabnzbd:/config
      - vol_downloads:/downloads
    networks:
      net_sabnzbd: null
    labels:
      - com.centurylinklabs.watchtower.enable=true
