---
version: "3"
networks:
  net_homeassistant: null
  net_influxdb: null
  net_grafana: null
  net_promeheus: null
volumes:
  vol_nginx:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/nginx/run
      o: bind
  vol_prometheus:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/prometheus/run
      o: bind
  vol_grafana:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/grafana/run
      o: bind
  vol_homeassistant:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/homeassistant/run
      o: bind
  vol_influxdb_config:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/influxdb/config
      o: bind
  vol_influxdb_db:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/influxdb/db
      o: bind
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - vol_nginx:/data
    networks:
      net_grafana: null
      net_homeassistant: null
      net_promeheus: null
    labels:
      - com.centurylinklabs.watchtower.enable=true
  prometheus:
    image: prom/prometheus
    volumes:
      - vol_prometheus:/etc/prometheus
    networks:
      net_promeheus: null
    labels:
      - com.centurylinklabs.watchtower.enable=true
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: "host"
    volumes:
      - vol_homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    labels:
      - com.centurylinklabs.watchtower.enable=true
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      net_influxdb: null
    volumes:
      - vol_influxdb_config:/etc/influxdb2
      - vol_influxdb_db:/var/lib/influxdb2
    labels:
      - com.centurylinklabs.watchtower.enable=true
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    networks:
      net_grafana: null
      net_influxdb: null
    volumes:
      - vol_grafana:/var/lib/grafana
    labels:
      - com.centurylinklabs.watchtower.enable=true

