---
version: "3"
volumes:
  vol_nginx:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/nginx/run
      o: bind
  vol_grafana:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/grafana/run
      o: bind
  vol_homeassistant:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/homeassistant/run
      o: bind
  vol_influxdb_config:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/influxdb/config
      o: bind
  vol_influxdb_db:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/influxdb/db
      o: bind
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - vol_homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - com.centurylinklabs.watchtower.enable=true
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - vol_influxdb_config:/etc/influxdb2
      - vol_influxdb_db:/var/lib/influxdb2
    labels:
      - com.centurylinklabs.watchtower.enable=true
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - vol_grafana:/var/lib/grafana
    labels:
      - com.centurylinklabs.watchtower.enable=true
