---
- name: make extra foldars
  hosts: your_debian_servers
  become: yes

  vars:
    target_folders:
      - /opt/docker/mosquitto/config
      - /opt/docker/mosquitto/data
      - /opt/docker/mosquitto/log
  tasks:
    - name: Create folders
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items: "{{ target_folders }}"
