version: "3.8"
volumes:
  vol_grafana:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/grafana/run
      o: bind
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - vol_grafana:/var/lib/grafana
